create teachers dir + add llama 3 70b teacher
mlcommons/modeltune pull request #33
Opened 2024-07-22 17:24 UTC by tsunamit

- add first teacher model
- add readme with instructions on how to run with teacher annotator
- add readme with instructions on how to run with llama guard 2

TODO
- add mistral teacher
- add local peft annotators
- add other teacher models

2024-07-22 17:34 UTC, tsunamit commented on teachers/README.md
> +## Running teacher model labeling
This is how you'd run the annotators. In short, the teacher pyproject will install modelgauge from the local submodule, load the teacher dir annotators thanks to the python plugin architecture, and run as usual

2024-07-22 17:35 UTC, tsunamit commented on teachers/micro.csv
> +Prompt,Response,UID,SUT
well formatted csv file to run a small test on

2024-07-22 17:35 UTC, tsunamit commented on teachers/modelgauge/annotators/llama_3_70b_chat_annotator.py
> +class Llama3_70bChatAnnotator(CompletionAnnotator[SafetyModelResponse]):
Here's the llama 3 70b chat teacher annotator implementation. The more interesting part is likely in the prompts used

2024-07-22 17:36 UTC, tsunamit commented on teachers/modelgauge/column_converter.py
> +def main(
small script to help convert arbitrary csv's into the format that we expect for modelgauge.

2024-07-22 21:46 UTC, shaonag requested changes
LGTM after addressing the minor comments and keeping a FIXME for future for various self.model sources : Together API, Hugging Face etc. Thanks for getting this done so promptly, Ryan!

2024-07-22 21:46 UTC, shaonag commented on teachers/README.md
Design:I know that we are referring to this approach of automated AI labeling as 'teachers'. That is fine to call them that internally. For the sake of avoiding confusion in future, I think a more suitable name can be "annotations" and under that, we can have "automatic_annotation" and "human_annotation". This would go under "automatic_annotation". 
There is a separate ML sub topic called model distillation, which uses a teacher large model and then a smaller model that distills the knowledge from the teacher, we do not want to confuse this approach with model distillation modeling approaches if that makes sense.

2024-07-22 21:46 UTC, shaonag commented on teachers/modelgauge/safety_model_response.py
> +class SafetyModelResponse(BaseModel):
nit: Missing doc string

2024-07-22 21:46 UTC, shaonag commented on teachers/modelgauge/annotators/llama_3_70b_chat_annotator.py
> +_DEFAULT_MAX_CHAT_TOKENS = 4000
I am considering if having a config for automatic config will be useful. Instead of configuring individual annotators within their files, maybe have a separate "automatic_annotator_config" which configures the path to the model , token length etc. This config file will then be easy to update and call another annotator in future. We can have a dataclass for annotator config?

2024-07-22 21:46 UTC, shaonag commented on teachers/modelgauge/annotators/llama_3_70b_chat_annotator.py
> +            text=LABELER_SYS_PROMPT.format(taxonomy=MLC_TAXONOMY_0_5),
Based on the config file comment above, this then becomes config.LABELER_SYS_PROMPT and config.MLC_TAXONOMY

2024-07-22 21:46 UTC, shaonag commented on teachers/modelgauge/annotators/llama_3_70b_chat_annotator.py
> +        self.model = TogetherChatSUT(uid, LLAMA_3_70B_MODEL_PATH, together_api_key)
Ideally self.model should be able to handle both Hugging Face models or any other API based models. Fine for now in the interest of time. Maybe something we can update later.

2024-07-23 02:52 UTC, tsunamit commented on teachers/README.md
good idea for the restructure

2024-07-23 03:01 UTC, tsunamit commented on teachers/modelgauge/annotators/llama_3_70b_chat_annotator.py
> +_DEFAULT_MAX_CHAT_TOKENS = 4000
great idea - created configs

2024-07-23 03:21 UTC, shaonag approved these changes
LGTM. All comments addressed. OK to merge.

2024-07-23 03:38 UTC, bollacker approved these changes

2024-07-23 03:40 UTC, merged